# Generated by Django 4.1.7 on 2023-02-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_register', '0002_beginiaimetrai_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('pavarde', models.CharField(max_length=100)),
                ('paimaina', models.CharField(choices=[('PIRMA', 'pirma'), ('ANTRA', 'antra'), ('TRECIA', 'trecia')], default='PIRMA', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
