# Generated by Django 4.1.7 on 2023-02-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_register', '0003_darbuotojas_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darbuotojas',
            old_name='paimaina',
            new_name='pamaina',
        ),
    ]
