# Generated by Django 4.1.7 on 2023-02-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_register', '0004_rename_paimaina_darbuotojas_pamaina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrai', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pamaina', models.CharField(choices=[('PIRMA', 'pirma'), ('ANTRA', 'antra'), ('TRECIA', 'trecia')], default='PIRMA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SawBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='beginiaimetrai',
            name='pjuklas',
        ),
        migrations.DeleteModel(
            name='Darbuotojas',
        ),
        migrations.DeleteModel(
            name='BeginiaiMetrai',
        ),
        migrations.DeleteModel(
            name='Pjuklas',
        ),
        migrations.AddField(
            model_name='saw',
            name='saw_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_register.sawbrand'),
        ),
        migrations.AddField(
            model_name='meter',
            name='saw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool_register.saw'),
        ),
    ]
