# Generated by Django 4.1.7 on 2023-02-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_register', '0007_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawbrand',
            name='workplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool_register.workplace'),
            preserve_default=False,
        ),
    ]
