# Generated by Django 4.1.5 on 2023-02-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tool_register", "0008_sawbrand_workplace"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meter",
            old_name="metrai",
            new_name="metres",
        ),
    ]
