# Generated by Django 4.1.5 on 2023-02-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tool_register", "0009_rename_metrai_meter_metres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meter",
            old_name="metres",
            new_name="meters",
        ),
    ]
