# Generated by Django 4.1.7 on 2023-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tool_register", "0010_rename_metres_meter_meters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="saw",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tool_register.saw",
            ),
        ),
        migrations.AlterField(
            model_name="saw",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
