# Generated by Django 4.1.5 on 2023-02-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SawRegister", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SawName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="SawName")),
            ],
        ),
        migrations.AlterField(
            model_name="jobcenter",
            name="name",
            field=models.CharField(
                help_text="Select or create job center",
                max_length=50,
                verbose_name="Name",
            ),
        ),
        migrations.RemoveField(
            model_name="saw",
            name="name",
        ),
        migrations.AlterField(
            model_name="saw",
            name="shift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saw",
            name="name",
            field=models.ManyToManyField(
                help_text="Išsirinkite pjūklą", to="SawRegister.sawname"
            ),
        ),
    ]
